[package]
name = "tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["http2", "ws"] }

pnet = "0.35.0"
serde = {version= "1.0.219",features = ["derive","rc"]}
serde_json = "1.0.140"
tokio = {version = "1.45.0",features = ["full"]}
